### ISSUE TITLE
Typo in MATH323 Notes

### ISSUE THREAD

**Issue by krubenok** [abrandenberger/course-notes#1]
Your (excellent) notes for MATH323 contain a small very nitpick-y typo on page 16. 

![img_aac82528beb9-1](https://user-images.githubusercontent.com/2529120/49488780-16c86180-f816-11e8-9507-bca55f6ee488.jpeg)

**Comment by abrandenberger** [comment]
Fixed! (after 2 months lol)

**Comment by krubenok** [comment]
LOL no problem! Great notes by the way!
