### ISSUE TITLE
Release LaTeX sources

### ISSUE THREAD

**Issue by toshokan** [abrandenberger/course-notes#2]
Have you considered releasing the LaTeX sources for your notes?
It would be easier for others to contribute (or reuse pieces) that way.

Also, what license are these released under? It's unclear whether we are free to reuse or redistribute these notes.

**Comment by abrandenberger** [comment]
Added a license - go ahead and reuse/redistribute the notes, just keep the credits. 
As for the LaTeX source code, right now it's quite messy, but some day I'll clean it up and make a template. For something less complex that you can customize yourself, look for the Tufte template.
